name: FloatingTips
author: lorenzo.stanco
category: Interface
tags: [tip, tooltip, balloon, tips]
demo: http://jsfiddle.net/yAWDT/400/
docs: http://wiki.github.com/lorenzos/FloatingTips/docs
current: 2.2
sources:
- "Source/floatingtips.js"